<?php
$helper = Mage::helper('ajaxcategory');
if (!$helper->isEnabled()) { 
	return; 
}

$actionName = $this->getAction()->getFullActionName();
if ($actionName == 'catalog_category_view') 
{
	$mode = $this->getLayout()->createBlock('catalog/product_list_toolbar')->setChild('product_list_toolbar_pager', $pager)->getCurrentMode();
	
    $category = Mage::registry('current_category');
    $prodCol = $category->getProductCollection()->addAttributeToFilter('status', 1)->addAttributeToFilter('visibility', array('in' => array(Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG, Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH)));
    $tool = $this->getLayout()->createBlock('page/html_pager')->setLimit($this->getLayout()->createBlock('catalog/product_list_toolbar')->getLimit())->setCollection($prodCol);
    $linkPrev = false;
    $linkNext = false;
    if ($tool->getCollection()->getSelectCountSql()) {
        if ($tool->getLastPageNum() > 1) {
            if (!$tool->isFirstPage()) {
                $linkPrev = true;
                if ($tool->getCurrentPage() == 2) {
                    $url = explode('?', $tool->getPreviousPageUrl());
                    $prevUrl = @$url[0];
                }
                else {
                    $prevUrl = $tool->getPreviousPageUrl();
                }
            }
            if (!$tool->isLastPage()) {
                $linkNext = true;
                $nextUrl = $tool->getNextPageUrl();
            }
        }
    }
    if ($linkPrev) {
		echo '<link id="ekeAjaxPrev" rel="prev" href="' . $prevUrl . '" />';
	}
    if ($linkNext) {
		echo '<link id="ekeAjaxNext" rel="next" href="' . $nextUrl . '" />';
	}
}
?>

<script type="text/javascript">
jQuery.getScript("<?php echo $this->getJsUrl('eke/ajaxcategory/jquery-ias.js') ?>", function() {
jQuery(function() {

		var ias = jQuery.ias({
		  container : "<?php echo $helper->getContainerSelector(); ?>",
		  item		: "<?php if($mode == 'grid'){ echo $helper->getGridSelector(); } else {echo $helper->getListSelector(); }?>",
		  next		: "#ekeAjaxNext"
		});
		
		ias.extension(new IASPagingExtension());
		ias.extension(new IASSpinnerExtension({ html: '<div style="text-align: center;"><img style="display:inline" src="<?php echo $this->getSkinUrl('images/ajaxcategory/loading.svg'); ?>"/></div>' }));
		ias.extension(new IASNoneLeftExtension({text: '<?php echo $helper->getNoMore(); ?>'}));

		jQuery.ias().on('pageChange', function(pageNum, scrollOffset, url) {
			window.history.pushState('','',url)
		});

	});
});
</script>