
<div class="heading">
	<h3><?php echo $this->__('Order Summary') ?></h3>
</div>

<?php $_items = $this->getItems() ?>

<?php if(count($_items)): ?>
	<div id="eke_FCsummary" class="col-sm-12">
	<?php foreach($_items as $_item): ?>
		<?php echo $this->getItemHtml($_item) ?>
	<?php endforeach; ?>
	</div>
<?php else: ?>
	<p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
<?php endif ?>




<div class="summary">
Subtotal<br>
Shipping<br>
Total
    <p class="subtotal">
        <?php if ($this->canApplyMsrp()): ?>
            <span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
        <?php else: ?>
            <span class="label"><?php echo $this->__('Cart Subtotal:') ?></span> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
            <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                <br />(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
            <?php endif; ?>
        <?php endif; ?>
    </p>
</div>


