<?php
$helper = Mage::helper("eke_avant");
if (!$helper->isAvantMetaEnabled()) {
    return;
}

$siteid = $helper->getAvantSiteid();
?>

<!-- AvantLink Standard Tracking -->
<script type="text/javascript">
(function() {
var avm = document.createElement('script'); avm.type = 'text/javascript'; avm.async = true;
avm.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.avmws.com/<?php echo $siteid; ?>/';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(avm, s);
})();
</script>

