<div class="order-info-box">

    <h2 class="table-caption">Tack Order Delivery</h2>
    <div style="height:500px;" id="map"></div>

</div>
 <?php 



$trackingNumber = 9405516901654213938584;

$xml = rawurlencode("
    <TrackID ID=\"9405516901654213938584\"></TrackID>
    </TrackFieldRequest>");
$request = "http://production.shippingapis.com/ShippingAPI.dll?API=TrackV2&XML=<?xml%20version=\"1.0\"%20encoding=\"UTF-8\"%20?><Revision>1</Revision><TrackFieldRequest%20PASSWORD=\"\"%20USERID=\"966EKEDI7934\"%20APPID=\"\">" . $xml;
echo $request . '<br /><br /><br /><br />';

// send the POST values to USPS
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,$request);
curl_setopt($ch, CURLOPT_HEADER, false);
curl_setopt($ch, CURLOPT_HTTPGET, true);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);


$result = curl_exec($ch);

curl_close($ch);

//$response = new SimpleXMLElement($result);
//$response_array = json_decode(json_encode($response),true);

print_r($result);
 /*
foreach($response_array as $response){
	foreach($response['TrackDetail'] as $details){
		
		if (0 === strpos($details, 'Arrived ')) {
			//echo $details.'<br />';
			$details = explode(",", $details);
			$zip = $details[5];
			$zip = preg_replace("/[^0-9,.]/", "", $zip);
			
			
			$url = "http://api.geonames.org/postalCodeSearch?postalcode=".$zip."&username=ekedigital";
			$ch = curl_init();
			curl_setopt($ch, CURLOPT_URL, $url);
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
			curl_setopt($ch, CURLOPT_PROXYPORT, 3128);
			curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
			curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
			$response = curl_exec($ch);
			curl_close($ch);
			$response_a = new SimpleXMLElement($response);
			$response_a_array = json_decode(json_encode($response_a),true);			
			
			foreach($response_a_array['code'] as $zipDetails){
				//print_r($zipDetails);
				$countryCheck = $zipDetails['countryCode'];
				
				if($countryCheck == 'US'){
					$lat = $zipDetails['lat'];
					$long = $zipDetails['lng'];
					$d4rkString .= "{lat: $lat, lng: $long},";
				}
			}

		}
	
	}
}

*/
//echo "LAT DETAILS: $d4rkString";

$d4rkString = rtrim($d4rkString, ',');
 
 ?>
 
 

 
    <script>

      function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 3,
          center: {lat: 25.90966, lng: -80.247} ,
          mapTypeId: 'terrain'
        });

        var flightPlanCoordinates = [
          <?php echo $d4rkString; ?>
        ];
        var flightPath = new google.maps.Polyline({
          path: flightPlanCoordinates,
          geodesic: true,
          strokeColor: '#FF0000',
          strokeOpacity: 1.0,
          strokeWeight: 2
        });

        flightPath.setMap(map);
      }
    </script>
    
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAGW8TBVdcpyjp7tNA6CB18Ol0wM2U1_EI&callback=initMap"> </script>