<?php
/* $helper = Mage::helper("eke_ogmeta");
if (!$helper->isOgMetaEnabled()) {
    return;
}
$siteName = $helper->getSiteName();
*/

$_option = Mage::registry('current_product')->getOption();

var_dump($_option);
$_optionTitle = Mage::registry('current_product')->getOptions()->getTitle();
$_optionRequired = Mage::registry('current_product')->getOptions()->getIsRequire();
$_optionType = Mage::registry('current_product')->getOptions()->getType();

?>


<dt><label<?php if ($_optionRequired) echo ' class="required"' ?>><?php if ($_optionRequired) echo '<em>*</em>' ?><?php echo  $this->escapeHtml($_option->getTitle()) ?></label></dt>
<dd<?php if ($_option->decoratedIsLast){?> class="last"<?php }?>>
    <div class="input-box">
        <?php echo $this->getValuesHtml() ?>
        <?php if ($_option->getIsRequire()): ?>
            <?php if ($_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_RADIO || $_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_CHECKBOX): ?>
                <span id="options-<?php echo $_option->getId() ?>-container"></span>
            <?php endif; ?>
        <?php endif;?>
    </div>
</dd>

